spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

itemImgLocation: /solbin/project/upload/shop
uploadPath: file:///solbin/project/upload
